apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: $name
  name: $name
spec:
  replicas: 1
  selector:
    matchLabels:
      run: $name
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: $name
    spec:
      containers:
      - image: $image
        name: $name
        env:
        - name: APP_NAME
          value: $name
        - name: APP_VERSION
          value: $version
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          httpGet:
            path: /health
            port: management
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          httpGet:
            path: /health
            port: management
        ports:
        - name: http
          containerPort: 8080
        - name: management
          containerPort: 9080

      restartPolicy: Always