# An example properties file that will work with https://github.com/SprintHive/ship

spring:
  data:
    mongodb:
      host: mongodb.local.svc.cluster.local
logging.fluent-bit.host: fluent-bit.infra.svc.cluster.local:5170